# Generated by Django 4.1 on 2023-12-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_cartlist_alter_categ_options_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.categ', verbose_name='category'),
        ),
    ]
