# Generated by Django 4.1 on 2023-12-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_alter_product_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='diff',
        ),
    ]
