# Generated by Django 4.1 on 2023-12-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_remove_product_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoryname',
            field=models.CharField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
