# Generated by Django 4.1 on 2023-12-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_product_categoryname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryname',
            new_name='namecategory',
        ),
    ]
