# Generated by Django 4.1 on 2023-12-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_alter_cartlist_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='cartid',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
