# Generated by Django 4.1 on 2023-12-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_alter_cartlist_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='cartid',
            field=models.CharField(default=1, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
